<?php

#-------------------------------------------------------
#
# OPEN RESUME by Don Westendorp
# © 2016 - Released under GPL v3 Licensing
#
# language/english/email.php
# Loads english language localization for emails
#
#-------------------------------------------------------


# Contact Form Email language
define('LANG_EMAIL_RECEIVED_MESSAGE','You\'ve received a message from the contact form on your resume:');
define('LANG_EMAIL_LOGIN_TO_ADMIN','Login to your admin panel to manage messages');
define('LANG_EMAIL_GENERATED_BY','This email generated by OpenResume ');
define('LANG_CONTACT_EMAIL_SUBJECT','OpenResume - New message from ');




?>