<?php

#-------------------------------------------------------
#
# OPEN RESUME by Don Westendorp
# © 2016 - Released under GPL v3 Licensing
#
# language/english/frontend.php
# Loads english language localization for the front end
#
#-------------------------------------------------------


# view/c_render_resume.php


# view/c_render_contact_form.php
define('LANG_CONTACT_ME','Contact Me');
define('LANG_LOCATED_IN','Located In');
define('LANG_SEND_MESSAGE','Send Message');
define('LANG_SEND_ME_A_MESSAGE','Send Me A Message');
define('LANG_YOUR_NAME','Your Name');
define('LANG_YOUR_EMAIL','Your Email');
define('LANG_YOUR_MESSAGE','Your Message');

define('LANG_CONTACT_SUCCESS','Message Sent');
define('LANG_CONTACT_MESSAGE_RECEIVED','Thank you for contacting me');
define('LANG_CONTACT_MESSAGE_CLOSE','Closing in');

# controller/c_contact_controller.php
# Contact Email language
define('LANG_EMAIL_RECEIVED_MESSAGE','You\'ve received a message from the contact form on your resume:');
define('LANG_EMAIL_LOGIN_TO_ADMIN','Login to your admin panel to manage messages');
define('LANG_EMAIL_GENERATED_BY','This email generated by OpenResume ');
define('LANG_EMAIL_SUBJECT','OpenResume - New message from ');

# verify.php
# These are the error messages for the form processor
define('LANG_AND','and');
define('LANG_CHARACTERS','Characters');

define('LANG_INVALID_DATE','Invalid date');
define('LANG_INVALID_DECIMAL_VALUE','Invalid decimal value');
define('LANG_INVALID_EMAIL_ADDRESS','Invalid email address');
define('LANG_INVALID_END_DATE','Invalid End Date');
define('LANG_INVALID_FORMAT','Invalid format');
define('LANG_INVALID_MONETARY_VALUE','Invalid monetary value');define('LANG_INVALID_URL','Invalid URL');
define('LANG_INVALID_POSTCODE','Invalid postcode');
define('LANG_INVALID_START_DATE','Invalid Start Date');
define('LANG_MUST_BE','Must be');
define('LANG_MUST_BE_10_DIGITS_LONG','Must be 10 digits long');
define('LANG_MUST_BE_AT_LEAST','Must be at least');
define('LANG_MUST_BE_AT_MOST','Must be at most');
define('LANG_MUST_BE_BETWEEN','Must be between');
define('LANG_MUST_BE_GREATER_THAN','Must be greater than');
define('LANG_MUST_BE_LESS_THAN','Must be less than');
define('LANG_NUMBER_MUST_START_WITH_0','Number must start with 0');
define('LANG_PLEASE_SELECT_AN_OPTION','Please select an option');
define('LANG_STREET_NUMBER_ONLY','Street Number only');
define('LANG_START_DATE_MUST_COME_BEFORE_END_DATE','Start Date must come before End Date');
define('LANG_THIS_CHECKBOX_IS_REQUIRED','This checkbox is required');
define('LANG_THIS_FIELD_IS_REQUIRED','This field is required');
define('LANG_USE_DIGITS_AND_LETTERS_ONLY','Use digits and letters only');
define('LANG_USE_DIGITS_AND_SPACES_ONLY','Use digits and spaces only');
define('LANG_USE_DIGITS_ONLY','Use digits only');
define('LANG_YOU_MUST_AGREE_TO_CONTINUE','You must agree to continue');
define('LANG_YOU_MUST_BE_AT_LEAST','You must be at least');





?>